// <auto-generated />
using System;
using DataReconciliationEngine.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataReconciliationEngine.Infrastructure.Migrations
{
    [DbContext(typeof(ReconciliationDbContext))]
    [Migration("20260213104042_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.ComparisonResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ComparedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComparisonConfigId")
                        .HasColumnType("int");

                    b.Property<bool>("ExistsInSystemA")
                        .HasColumnType("bit");

                    b.Property<bool>("ExistsInSystemB")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<string>("LogicalFieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchKeyValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.Property<string>("ValueSystemA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueSystemB")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComparisonResults");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.ComparisonRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComparisonConfigId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalMismatches")
                        .HasColumnType("int");

                    b.Property<int>("TotalMissingInA")
                        .HasColumnType("int");

                    b.Property<int>("TotalMissingInB")
                        .HasColumnType("int");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComparisonRuns");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.FieldMappingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComparisonConfigId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogicalFieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemA_Column")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemB_Column")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonConfigId");

                    b.ToTable("FieldMappingConfigurations");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComparisonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatchColumn_SystemA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchColumn_SystemB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemA_Table")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemB_Table")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TableComparisonConfigurations");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.FieldMappingConfiguration", b =>
                {
                    b.HasOne("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", "ComparisonConfig")
                        .WithMany("FieldMappings")
                        .HasForeignKey("ComparisonConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComparisonConfig");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", b =>
                {
                    b.Navigation("FieldMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
