// <auto-generated />
using System;
using DataReconciliationEngine.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataReconciliationEngine.Infrastructure.Migrations
{
    [DbContext(typeof(ReconciliationDbContext))]
    [Migration("20260219135417_AddCustomerSitesDuplicateDetection")]
    partial class AddCustomerSitesDuplicateDetection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.ComparisonResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ComparedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComparisonConfigId")
                        .HasColumnType("int");

                    b.Property<bool>("ExistsInSystemA")
                        .HasColumnType("bit");

                    b.Property<bool>("ExistsInSystemB")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<string>("LogicalFieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatchKeyValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.Property<string>("ValueSystemA")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValueSystemB")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonConfigId");

                    b.HasIndex("RunId", "IsMatch")
                        .HasDatabaseName("IX_ComparisonResults_RunId_IsMatch");

                    b.HasIndex("RunId", "LogicalFieldName")
                        .HasDatabaseName("IX_ComparisonResults_RunId_LogicalFieldName");

                    b.HasIndex("RunId", "MatchKeyValue")
                        .HasDatabaseName("IX_ComparisonResults_RunId_MatchKeyValue");

                    b.ToTable("ComparisonResults");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.ComparisonRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComparisonConfigId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RunType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TotalMismatches")
                        .HasColumnType("int");

                    b.Property<int>("TotalMissingInA")
                        .HasColumnType("int");

                    b.Property<int>("TotalMissingInB")
                        .HasColumnType("int");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonConfigId", "RunDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ComparisonRuns_ConfigId_RunDate");

                    b.HasIndex("RunType", "RunDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ComparisonRuns_RunType_RunDate");

                    b.ToTable("ComparisonRuns");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.DuplicateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CertainCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("LatRound")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("LonRound")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("ProbableCount")
                        .HasColumnType("int");

                    b.Property<int>("RecordsCount")
                        .HasColumnType("int");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "CandidateKey")
                        .HasDatabaseName("IX_DuplicateGroups_RunId_CandidateKey");

                    b.HasIndex("RunId", "RecordsCount")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_DuplicateGroups_RunId_RecordsCount");

                    b.ToTable("DuplicateGroups");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.DuplicateRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxNorm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BoxRaw")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CityNorm")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CityRaw")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CompletenessScore")
                        .HasColumnType("int");

                    b.Property<int>("CustomerSitesId")
                        .HasColumnType("int");

                    b.Property<int>("DuplicateGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMasterSuggested")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(17, 14)
                        .HasColumnType("decimal(17,14)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(17, 14)
                        .HasColumnType("decimal(17,14)");

                    b.Property<string>("NumberNorm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumberRaw")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StreetNorm")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StreetRaw")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZipNorm")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZipRaw")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerSitesId")
                        .HasDatabaseName("IX_DuplicateRecords_CustomerSitesId");

                    b.HasIndex("DuplicateGroupId")
                        .HasDatabaseName("IX_DuplicateRecords_DuplicateGroupId");

                    b.ToTable("DuplicateRecords");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.FieldMappingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComparisonConfigId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogicalFieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SystemA_Column")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SystemB_Column")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonConfigId");

                    b.ToTable("FieldMappingConfigurations");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComparisonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatchColumn_SystemA")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MatchColumn_SystemB")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SystemA_Table")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SystemB_Table")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonName")
                        .IsUnique()
                        .HasDatabaseName("IX_TableComparisonConfigs_ComparisonName");

                    b.ToTable("TableComparisonConfigurations");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.ComparisonResult", b =>
                {
                    b.HasOne("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", null)
                        .WithMany()
                        .HasForeignKey("ComparisonConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataReconciliationEngine.Domain.Entities.ComparisonRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.ComparisonRun", b =>
                {
                    b.HasOne("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", null)
                        .WithMany()
                        .HasForeignKey("ComparisonConfigId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.DuplicateGroup", b =>
                {
                    b.HasOne("DataReconciliationEngine.Domain.Entities.ComparisonRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.DuplicateRecord", b =>
                {
                    b.HasOne("DataReconciliationEngine.Domain.Entities.DuplicateGroup", null)
                        .WithMany("Records")
                        .HasForeignKey("DuplicateGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.FieldMappingConfiguration", b =>
                {
                    b.HasOne("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", "ComparisonConfig")
                        .WithMany("FieldMappings")
                        .HasForeignKey("ComparisonConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComparisonConfig");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.DuplicateGroup", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", b =>
                {
                    b.Navigation("FieldMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
