// <auto-generated />
using System;
using DataReconciliationEngine.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataReconciliationEngine.Infrastructure.Migrations
{
    [DbContext(typeof(ReconciliationDbContext))]
    partial class ReconciliationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.ComparisonResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ComparedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComparisonConfigId")
                        .HasColumnType("int");

                    b.Property<bool>("ExistsInSystemA")
                        .HasColumnType("bit");

                    b.Property<bool>("ExistsInSystemB")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<string>("LogicalFieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatchKeyValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.Property<string>("ValueSystemA")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValueSystemB")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonConfigId");

                    b.HasIndex("RunId", "IsMatch")
                        .HasDatabaseName("IX_ComparisonResults_RunId_IsMatch");

                    b.HasIndex("RunId", "LogicalFieldName")
                        .HasDatabaseName("IX_ComparisonResults_RunId_LogicalFieldName");

                    b.HasIndex("RunId", "MatchKeyValue")
                        .HasDatabaseName("IX_ComparisonResults_RunId_MatchKeyValue");

                    b.ToTable("ComparisonResults");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.ComparisonRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComparisonConfigId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalMismatches")
                        .HasColumnType("int");

                    b.Property<int>("TotalMissingInA")
                        .HasColumnType("int");

                    b.Property<int>("TotalMissingInB")
                        .HasColumnType("int");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonConfigId", "RunDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ComparisonRuns_ConfigId_RunDate");

                    b.ToTable("ComparisonRuns");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.FieldMappingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComparisonConfigId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogicalFieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SystemA_Column")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SystemB_Column")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonConfigId");

                    b.ToTable("FieldMappingConfigurations");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComparisonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatchColumn_SystemA")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MatchColumn_SystemB")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SystemA_Table")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SystemB_Table")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonName")
                        .IsUnique()
                        .HasDatabaseName("IX_TableComparisonConfigs_ComparisonName");

                    b.ToTable("TableComparisonConfigurations");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.ComparisonResult", b =>
                {
                    b.HasOne("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", null)
                        .WithMany()
                        .HasForeignKey("ComparisonConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataReconciliationEngine.Domain.Entities.ComparisonRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.ComparisonRun", b =>
                {
                    b.HasOne("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", null)
                        .WithMany()
                        .HasForeignKey("ComparisonConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.FieldMappingConfiguration", b =>
                {
                    b.HasOne("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", "ComparisonConfig")
                        .WithMany("FieldMappings")
                        .HasForeignKey("ComparisonConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComparisonConfig");
                });

            modelBuilder.Entity("DataReconciliationEngine.Domain.Entities.TableComparisonConfiguration", b =>
                {
                    b.Navigation("FieldMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
